### ISSUE TITLE
composer.json çalışmıyor

### ISSUE THREAD

**Issue by GoktugOzturk** [ibrahimgunduz34/p2-core#4]
Sanırım "name": "paranoiaproject/paranoia2", dediği fakat packagist'te bulamadığı için hata veriyor.

**Comment by ibrahimgunduz34** [comment]
Farklı bir konu ile ilgili hata almış olabilir misin ? Bende vermedi.

**Comment by GoktugOzturk** [comment]
Benden kaynaklı bir sıkıntı sanırım. Sebebini çözemedim.  
kapattım abi zaten issue'yu
